- .github/workflows/test.yml
- package-lock.json
> fix(workflows): Ajustanto o pipeline de testes

- src/base.ts
- src/types.ts
- tests/zendesk.test.ts
> fix: ajustando instanciacao classe Zendesk

- .github/workflows/delete-branch.yml
> ci(github): add delete branch workflow

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): v1.4.0

- CHANGELOG.md
- package-lock.json
- package.json
New release
- Package version
---
**Checklist:**
> chore: release v1.4.1

- src/base.ts
- src/types.ts
- tests/base.test.ts
_Add default headers to the requests initiated by the endpoints specified in the constructor of the class._
_This allows the user to define a header required for their requests._
---
**Checklist:**
> feat: add default headers to be used on endpoints construct requests

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): v1.5.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): v1.5.1

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): v1.5.2

- .github/workflows/code_quality.yml
> feat: add code quality check

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): v1.5.3

- CHANGELOG.md
- package-lock.json
- package.json
> release: Adding release notes for v1.5.4

- src/base.ts
- tests/base.test.ts
fix make request params in axios client.
---
**Checklist:**
> fix: make request params

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): v1.6.0

- src/zendesk.ts
- tests/zendesk.test.ts
Helper method to get current zendesk ticket data
- New zendesk client helper method
---
**Checklist:**
> feat: add get current ticket method to zendesk client

- CHANGELOG.md
- package-lock.json
- package.json
> chore: release v1.7.0

- src/zendesk.ts
adjusts get current ticket method return
- return data correctly
---
**Checklist:**
> fix: get current ticket

- .github/workflows/auto-assign.yml
- .github/workflows/auto-labeler.yml
- .github/workflows/delete-branch.yml
- .github/workflows/npm-publish.yml
- .github/workflows/release-drafter.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
Use workflows from aktie-devops repository
- use reusable workflows
---
**Checklist:**
> chore: add reusable workflows

- CHANGELOG.md
- package-lock.json
- package.json
> chore: bump version to v1.7.2

- .github/workflows/npm-publish.yml
> chore: add npm token

- src/types.ts
- src/zendesk.ts
- tests/zendesk.test.ts
Add new zendesk implementations to help in sending data between different locations
- add new implementation to `createModal` method
- new method `triggerToLocations`
- new method `modalReady`
---
**Checklist:**
> feat: add zendesk helper methods

- CHANGELOG.md
- package-lock.json
- package.json
> chore: bump version to v1.8.0

- CHANGELOG.md
- package-lock.json
- package.json
**Descrição:**
release v1.8.1
---
**Checklist:**
> release:v1.8.1

- CHANGELOG.md
- package-lock.json
- package.json
**Descrição:**
release:v1.8.3
---
**Checklist:**
> release:v1.8.3

- src/zendesk.ts
**Descrição:**
_Corrige o incremento da propriedade retry count no tratamento das retentativas._
---
**Checklist:**
> fix: properly increases the retry count

- package.json
- src/utils.ts
- tests/utils.test.ts
**Descrição:**
_Corrige a função `queryParamsUrl` para lidar corretamente com múltiplos parâmetros_
---
**Checklist:**
> fix: properly parse query params
